#!/usr/local/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export LD_PRELOAD=${DIR}/libpreload.so
export ALLOWED_FOR_CREATE=/tmp 
export ALLOWED_FOR_READ=/usr/local/dlang.org/asm/compilers:/tmp:/dev/urandom:/proc/self:/proc/self/maps
export DENIED=/proc/self/cwd:/proc/self/root:/proc/self/exe

# Wine configuration
export DISPLAY=
export WINEPREFIX=/tmp/wine
mkdir -p /tmp/wine
ALLOWED_FOR_READ=${ALLOWED_FOR_READ}:/usr/share/fonts:/etc/passwd

# Last-gasp limits
ulimit -m $((512 * 1024)) # RSS limit in K
ulimit -t 10 # CPU time in seconds
ulimit -v $((2 * 1024 * 1024)) # virtual RAM limit in K

"$@"
