executionType=none
firejail=
sandboxType=none
wine=
winePrefix=/tmp/ce-wine-prefix
wineServer=
firejail.profile.execute=etc/firejail/execute.profile
firejail.profile.sandbox=etc/firejail/sandbox.profile
firejail.profile.wine=etc/firejail/wine.profile
